name: test-confinement
base: core22
version: '0.1'
summary: Demo some confinment bits
description: |
  Demo some snap confinement and interface items.

grade: devel
confinement: strict

apps:
  bash:
    command: bash
    #plugs: 
    #  - home

parts:
  bash:
    plugin: autotools
    source: https://ftp.gnu.org/gnu/bash/bash-5.2.tar.gz
    autotools-configure-parameters: ["--infodir=/var/bash/info"]
    build-packages: [ build-essential ]
    organize:
      usr/local/bin/bash: bash
